---
name: Pi-Bot Build Image

# yamllint disable-line rule:truthy
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Log into registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ghcr.io/scioly/pi-bot

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          file: prod.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/pi-bot:${{ github.sha }}
